name: CI


on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]


jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Permission giving
        run: ./gradlew build
        
      - name: Spotless applied
        run: .\/gradlew spotlessApply

  # simulate:
  #   runs-on: ubuntu-latest
  #   container: wpilib/roborio-cross-ubuntu:2024-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Grant execute permission for gradlew
  #       run: chmod +x gradlew
  #     - name: Simulate code
  #       run: ./gradlew simulateJava

  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Permission giving
        run: .\gradlew clean

      - name: Compile and run tests on robot code
        run: ./gradlew build
